### ISSUE TITLE
Orchestrator: zookeeper url

### ISSUE THREAD

**Issue by davidemalagoli** [crowdrec/idomaar#32]
Zookeeper url has to be determined by vagrant from datastreammanager machine

**Comment by andras-sereny** [comment]
Hi Davide, 
what do you exactly mean here? The IP address of the datastreammanager VM is defined in the Vagrantfile, Zookeeper is installed via the Debian package on the VM, so presumably it is configured to use the standard port 2181. Shall we somehow have a variable outside the VM that we use to configure the Zookeeper port ourselves? Or check the /etc/zookeeper/conf/zoo.cfg in the VM?Neither way seems less fragile than hardcoding the port, as it is now.

Thanks,
András

**Comment by davidemalagoli** [comment]
Hi,
perhaps the best would be to specify outside the vm the config for that, I'll leave to you to choose the best option.

Thanks,
Davide
