### ISSUE TITLE
Orchestrator: integrate it into vm

### ISSUE THREAD

**Issue by davidemalagoli** [crowdrec/idomaar#36]
Orchestrator must run in datastreamanager vm (we need to also change it name in orchestrator), so to avoid any external dependency

**Comment by andras-sereny** [comment]
I think this means moving (most of) the orchestator.py script onto the datastreammanager VM, and running it there once the datastreammanager has booted. However, we still need a python/bash script on the host system to spin up the datastreammanager VM and the computing environment VM. So, we'd be left with this new script (and vagrant itself) as a dependency -- is that fine?

**Comment by davidemalagoli** [comment]
I think that could be fine, the goal is to have the minimum (and more standard as possible) number of components on the host. This to avoid any dependency and problem in using that, for example, in windows env (we had some compatibility problem with python and windows in the past)
