### ISSUE TITLE
Forward 8888 port error

### ISSUE THREAD

**Issue by robertoturrin** [crowdrec/idomaar#48]
When I start the orchestrator vm, I get the following error message:

There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* Forwarded port '8888' (host port) is declared multiple times
with the protocol 'tcp'.

**Comment by davidemalagoli** [comment]
Tested on linux and mac os (vagrant 1.7.2) with a modification in forwarding config, it should work
