### ISSUE TITLE
Strange message in recommendation request

### ISSUE THREAD

**Issue by davidemalagoli** [crowdrec/idomaar#52]
Hi,
I've tried to execute the demo script in order to integrate new evaluation logic and I've seen the following INFO msg on the logs:
INFO     [bg:reco-manager] 2015-07-09 12:20:34,121 (PollableSourceRunner-KafkaSource-r1) [INFO - eu.crowdrec.flume.plugins.interceptor.IdomaarRecommendationInterceptor.intercept(IdomaarRecommendationInterceptor.java:80)] Requesting recommendation for event [recommendation	44	1362093742	{"reclen":5}	{"subject":"user:16"}\t757365720931360931343336343434343238373838097B7D097B227265636C656E223A357D095B7B226964223A2231393037363638222C22726174696E67223A22372E30222C2272616E6B223A2231227D5D]

it seams quite strange the string after the \t, do you know what is generating that?

**Comment by andras-sereny** [comment]
This is what ZFrame.toString generates, see the toString method at https://github.com/zeromq/jeromq/blob/master/src/main/java/org/zeromq/ZFrame.java . I've now changed the .toString call to a better way of turning the ZFrame into string.
