### ISSUE TITLE
Problem with Kafka in NewsREEL

### ISSUE THREAD

**Issue by andreas-dai** [crowdrec/idomaar#53]
Running the NewsREEL Evaluation based on Idomaar Fails do to Problems with Kafka
![20150713__error](https://cloud.githubusercontent.com/assets/7116591/8671676/7948d38c-2a27-11e5-990c-1bee74261f6f.png)

**Comment by davidemalagoli** [comment]
I can't see the image, could you please upload it again?

**Comment by andreas-dai** [comment]
There is no image in the ticket, but just a log-File. Unfortunately, github does not allow uploading log files. In the internet Explorer clicking on the log-File shows the text. Converting the log into an image does not make sense to me.
