### ISSUE TITLE
Exception in the NewsREEL evaluation

### ISSUE THREAD

**Issue by chris3456** [crowdrec/idomaar#59]
I tried to test the NewsREEL tutorial step by step. All steps work fine, but during the evaluation run, an exception is thrown; the script does not report CTR values.  I do not understand why this happens since the missing jar seems to be at the right place. For me it seems to be a problem with the framework that hides the required class.
![newsreel-log-exception](https://cloud.githubusercontent.com/assets/15193321/10848849/3c9a4adc-7f1e-11e5-99e8-e17fe9893dfc.png)

**Comment by davidemalagoli** [comment]
Hi chris, sorry for the late answer, we are working on this and we'll provide a solution for that asap

**Comment by andras-sereny** [comment]
Should be working now if you build your idomaar from scratch with the lastest code.

**Comment by chris3456** [comment]
Hi andras-sereny, thank you very much for fixing the issue. I can confirm that the fix works for me. Now all steps explained in the NewsREEL tutorial work as expected. Thank you.
