### ISSUE TITLE
Error on recommendation manager

### ISSUE THREAD

**Issue by davidemalagoli** [crowdrec/idomaar#63]
Hi Andras,
I-ve tried to run the getting started (that use the mahout implmenetation) and it doesn't reach the evaluation phase correctly.

the only problem I see is in the datastreammanager - /var/log/flume-ng/recommendation-manager.log:
02 Dec 2015 14:20:32,369 ERROR [PollableSourceRunner-KafkaSource-r1] (org.apache.flume.source.kafka.KafkaSource.process:153)  - KafkaSource EXCEPTION, {}
java.lang.NullPointerException
	at org.apache.flume.instrumentation.MonitoredCounterGroup.increment(MonitoredCounterGroup.java:261)
	at org.apache.flume.instrumentation.kafka.KafkaSourceCounter.incrementKafkaEmptyCount(KafkaSourceCounter.java:49)
	at org.apache.flume.source.kafka.KafkaSource.process(KafkaSource.java:146)
	at org.apache.flume.source.PollableSourceRunner$PollingRunner.run(PollableSourceRunner.java:139)
	at java.lang.Thread.run(Thread.java:745)

but I think that is not related to the problem (even if no data reach the recommendation engine).

Do you have any idea on what could be? It should not be related to latest commit but I'm sure that this was working with release 3.

**Comment by andras-sereny** [comment]
Hi Davide, 
on a clean installation ./idomaar-demo.sh runs perfectly fine for me, computing:

NFO     [datastream] Recall@2: 0.2
INFO     [datastream] Recall@5: 0.2
INFO     [datastream] Recall@10: 0.2
INFO     [datastream] Mode: precision
INFO     [datastream] Precision: 0.047619047619

Have you built a new datastream vm from scratch? What are the last messages on your stdout from the orchestrator?

**Comment by andras-sereny** [comment]
One potential issue I see, though, is that eval.py runs on all files in the recommendation result directory, taking into account files produced by earlier runs as well.

**Comment by davidemalagoli** [comment]
are you using the master branch?

On Wed, Dec 2, 2015 at 4:40 PM, András Serény <notifications@github.com>
wrote:

> Assigned #63 <https://github.com/crowdrec/idomaar/issues/63> to
> @davidemalagoli <https://github.com/davidemalagoli>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/crowdrec/idomaar/issues/63#event-480319634>.
>



-- 
Davide Malagoli
Mobile: +39 345 6539950

**Comment by andras-sereny** [comment]
ah, no, let me try

**Comment by andras-sereny** [comment]
I've got the same successfull result with the master branch (no wonder, my branch is one insignificant commit behind the master).
