### ISSUE TITLE
The box you attempted to add doesn't match the provider you specified.

### ISSUE THREAD

**Issue by andreas-dai** [crowdrec/idomaar#65]
Trying to start the Virtual Machine on AWS I get get the following error message:
`andreas@dai160 /cygdrive/d/heute/idomaar-3.1-aws/computingenvironments/01.linux/01.centos/01.mahout`
`$ vagrant up --provider=aws`
`Bringing machine 'mahout' up with 'aws' provider... `
`==> mahout: Box 'dummy' could not be found. Attempting to find and install... `
`    mahout: Box Provider: aws`
`    mahout: Box Version: >= 0`
`==> mahout: Adding box 'dummy' (v0) for provider: aws`
`    mahout: Downloading: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box`
`    mahout: Progress: 100% (Rate: 8161k/s, Estimated time remaining: --:--:--) `
`The box you attempted to add doesn't match the provider you specified.`
`Provider expected: aws`
`Provider of box: virtualbox`

The same error also occurs on MacOS. I tested it with the Idomaar downloaded from `https://github.com/crowdrec/idomaar/releases/tag/v3.1-aws` (`.zip` and `.tgz`)

**Comment by davidemalagoli** [comment]
Could you try to add the dummy image with the following command:

"vagrant box add dummy
https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

if it works could you please also update the wiki or create an issue and assing it to me?

**Comment by andreas-dai** [comment]
I added the hint to the getting started guide.
