### ISSUE TITLE
Starting the VM failes

### ISSUE THREAD

**Issue by andreas-dai** [crowdrec/idomaar#66]
Trying to execute the Getting-Started-Guide on Linux (Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u6 x86_64 GNU/Linux) I get the following error message while running `vagrant up --provider=aws `:

`AWS Provider:`
`* An access key ID must be specified via "access_key_id"`
`* A secret access key is required via "secret_access_key"`

I tested vagrant v1.8.1 and 1.6.5 and 1.6.4.
![20160202__aws-test](https://cloud.githubusercontent.com/assets/7116591/12782465/c0814a1e-ca7b-11e5-9b2b-b310676ae1e4.png)

The same problem I also observe on cygwin.

**Comment by andreas-dai** [comment]
The problem seems to be the Vagrant file. Inserting the keys directly in the Vagrant file instead of defining a variable leads to a new error message.
![20160202__aws-test-s2](https://cloud.githubusercontent.com/assets/7116591/12791514/b58a4f76-caa7-11e5-924a-e459cc6d381e.png)

**Comment by davidemalagoli** [comment]
@andreas-dai we are not able to reproduce this error (tested both on windows vm, mac and linux), are you still getting the error? are you able to give me more hints on how to reproduce it?

**Comment by andreas-dai** [comment]
Having adapted the vagrant file, it works for me. We can close the issue.
