### ISSUE TITLE
The box you attempted to add doesn't match the provider you specified.

### ISSUE THREAD

**Issue by maranlar** [crowdrec/idomaar#67]
error when launching with vagrant up --provider=aws preceded by the other parameters:
The box you attempted to add doesn't match the provider you specified.

Provider expected: aws
Provider of box: virtualbox

Then she tried to hardcode the parameters in the vagrant file but she got:
vagrant up --provider=aws
Bringing machine 'mahout' up with 'aws' provider...
==> mahout: Box 'dummy' could not be found. Attempting to find and install...
   mahout: Box Provider: aws
   mahout: Box Version: >= 0
==> mahout: Adding box 'dummy' (v0) for provider: aws
   mahout: Downloading: https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box
The box you attempted to add doesn't match the provider you specified.

Provider expected: aws
Provider of box: virtualbox

Tester thinks the issue is relative to the creation of a VPC, the aws guide probably refers to a different version of the dashboard.

**Comment by davidemalagoli** [comment]
Hi,
it seams the same issue as https://github.com/crowdrec/idomaar/issues/65. Adreas has also update the guide to specify that the following command is required:
vagrant box add dummy https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box
