### ISSUE TITLE
Waiting for SSH to become available...

### ISSUE THREAD

**Issue by maranlar** [crowdrec/idomaar#68]
(Mac):
when executing the Start the computing environment command:
==> mahout: Warning! The AWS provider doesn't support any of the Vagrant
==> mahout: high-level network configurations (`config.vm.network`). They
==> mahout: will be silently ignored.
 gets stuck at: Waiting for SSH to become available...

**Comment by andreas-dai** [comment]
As far as I understand the Vagrant file, ssh uses the hard-coded key-pair named `idomaar`. In order to login, I edited the vagrant file defining that my personal key-pair should be used.

**Comment by maranlar** [comment]
Ah! If the participants need to do this, then it should be clearly explained in the directions. Thanks.

**Comment by davidemalagoli** [comment]
I've added configurable options (via environment variables) for:
- instance type
- keypair name
- region

updated also wiki to describe the new parameters
