### ISSUE TITLE
Recommendation requests are not dispatched using HTTP

### ISSUE THREAD

**Issue by dennismorello** [crowdrec/idomaar#77]
Hi,

I'm facing with this exception while computing environment is waiting for recommendation requests during the TEST phase (recommendation-manager.log file):
```
13 Jun 2016 09:32:48,494 ERROR [PollableSourceRunner-KafkaSource-r1] (org.apache.flume.source.kafka.KafkaSource.process:153)  - KafkaSource EXCEPTION, {}
java.lang.NullPointerException
	at org.apache.flume.instrumentation.MonitoredCounterGroup.increment(MonitoredCounterGroup.java:261)
	at org.apache.flume.instrumentation.kafka.KafkaSourceCounter.incrementKafkaEmptyCount(KafkaSourceCounter.java:49)
	at org.apache.flume.source.kafka.KafkaSource.process(KafkaSource.java:146)
	at org.apache.flume.source.PollableSourceRunner$PollingRunner.run(PollableSourceRunner.java:139)
	at java.lang.Thread.run(Thread.java:745)
```
Has somebody any idea to solve this issue? I'm using HTTP as communication protocol between computing environment and orchestrator.

**Comment by dennismorello** [comment]
Hi Andras, this bus seems to be related to [this](https://github.com/crowdrec/idomaar/issues/63) one.

I hope this helps.

**Comment by andras-sereny** [comment]
A strange error indeed. For me, running 

sudo /usr/bin/java -Xmx20m -Didomaar.url=https://raw.githubusercontent.com/crowdrec/data sets/master/01.MovieTweetings/datasets/snapshots_10K/evaluation/test/data.dat -Didomaar.sourceType=file -cp '/vagrant/flume-config/log4j/tes t:/opt/apache/flume/lib/*:/opt/apache/flume/plugins.d/idomaar/lib/*:/opt/apache/flume/plugins.d/idomaar/libext/*:/lib/*' -Djava.library.path = org.apache.flume.node.Application --name a1 --conf-file /vagrant/flume-config/config/generated/idomaar-TO-kafka-test.conf

on the datastream manager sometimes succeeds and sometimes fails with the java.lang.NoClassDefFoundError: Could not initialize class com.yammer.metrics.Metrics error. Apparently, the Metrics class *is* on the classpath.

Once I hack a call of com.yammer.metrics.Metrics into IdomaarSource initialization, the command succeeds consistently. I'm guessing this is some strange race condition in the Metrics class static initalization. If all is fine, I'll commit the hack on Monday.

**Comment by andras-sereny** [comment]
Apparently, Metrics is being initialized rather late, when the JVM is already shutting down, thus it fails to add a shutdown hook ... I'm not sure why. Timely initialization should fix this.

**Comment by dennismorello** [comment]
Ok András, can you commit the bug fix when you are ready? Thanks!

2016-06-17 16:53 GMT+02:00 András Serény <notifications@github.com>:

> Apparently, Metrics is being initialized rather late, when the JVM is
> already shutting down, thus it fails to add a shutdown hook ... I'm not
> sure why. Timely initialization should fix this.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/crowdrec/idomaar/issues/77#issuecomment-226791015>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ASrmBYsmY46CN30o7_R99lU8CUh1aXOPks5qMrTygaJpZM4I0LOY>
> .
>



-- 
[image: CW Logo (no word).jpg]

Dennis Morello  |  ContentWise R&D

*ContentWise* | Digital TV. Personalized.


M: +39 340 487 8469 <%2B39%20340%204878469>  |   www.contentwise.tv

Skype: dennis.morello

Via Schiaffino 11, 20158 Milano - Italy

**Comment by andras-sereny** [comment]
fixed
